const $=id=>document.getElementById(id);let status='pending',posts=[],selected=null,counts={},offset=0,dirty=false,loadGeneration=0;
const statusLabels={pending:'Chờ duyệt',published:'Đã đăng',rejected:'Đã loại'};
const topicLabels={space:'Vũ trụ',science:'Khoa học',nature:'Thiên nhiên',culture:'Nghệ thuật',everyday:'Đời sống'};
function n(tag,cls,text){const el=document.createElement(tag);if(cls)el.className=cls;if(text!==undefined)el.textContent=text;return el;}
function message(text){$('message').textContent=text;$('message').hidden=!text;}
function loggedIn(yes){$('login-view').hidden=yes;$('workspace').hidden=!yes;$('logout').hidden=!yes;if(!yes){posts=[];selected=null;dirty=false;$('queue').replaceChildren();$('editor').replaceChildren(n('p','empty','Chọn một bài để xem và chỉnh sửa.'));}}
async function api(path,options={}){const response=await fetch('/api/'+path,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json',...options.headers}});let body;try{body=await response.json();}catch{throw new Error('Chưa kết nối backend. Mở trang admin từ địa chỉ backend sau khi cài đặt.');}if(!response.ok){if(response.status===401)loggedIn(false);throw new Error(body.error||'Không thực hiện được thao tác.');}return body;}
function leave(){return !dirty||confirm('Bạn có thay đổi chưa lưu. Bỏ thay đổi này?');}
function tabs(){ $('status-tabs').replaceChildren(...Object.entries(statusLabels).map(([key,label])=>{const b=n('button',key===status?'active':'',`${label} · ${counts[key]||0}`);b.type='button';b.setAttribute('aria-pressed',String(key===status));b.onclick=()=>{if(!leave())return;status=key;dirty=false;selected=null;load();};return b;}));}
function queue(){ $('queue').replaceChildren(...posts.map(p=>{const b=n('button','queue-item'+(selected?.id===p.id?' selected':''));b.type='button';b.append(n('span','',p.source_name+' · '+topicLabels[p.topic]),n('strong','',p.vi.title||p.en.title||p.original_title),n('span','',(!p.vi.title?'Cần bản tiếng Việt · ':'')+statusLabels[p.status]));b.onclick=()=>{if(!leave())return;selected=p;dirty=false;queue();editor();};return b;}));if(!posts.length)$('queue').append(n('p','empty','Không có bài ở mục này.'));}
async function load(append=false){const generation=++loadGeneration;$('queue-more').disabled=true;try{const result=await api(`admin/posts?status=${status}&offset=${append?offset:0}`);if(generation!==loadGeneration)return;posts=append?[...posts,...result.posts]:result.posts;counts=result.counts;offset=posts.length;$('queue-more').hidden=!result.has_more;tabs();queue();if(!append){selected=null;dirty=false;editor();}}catch(e){if(generation===loadGeneration)message(e.message);}finally{if(generation===loadGeneration)$('queue-more').disabled=false;}}
function field(label,name,value,multiline=false){const l=n('label','field',label),el=n(multiline?'textarea':'input');el.name=name;el.value=value||'';el.maxLength=name.includes('title')?180:name.includes('summary')?1000:name==='review_note'?2000:2000;l.append(el);return l;}
function editor(){const root=$('editor');root.replaceChildren();if(!selected){root.append(n('p','empty','Chọn một bài để xem và chỉnh sửa.'));return;}
 const p=selected;root.append(n('h2','',p.status==='published'?'Chỉnh sửa bài đã đăng':'Đọc nguồn. Chọn điều hay.'));
 const source=n('a','source-link','Mở bài gốc · '+p.source_name);source.href=p.source_url;source.target='_blank';source.rel='noopener noreferrer';root.append(source);
 const original=n('details','original');original.append(n('summary','',p.original_title||'Nội dung nguồn'),n('p','',p.source_excerpt||'Mở link nguồn để đọc nội dung.'));root.append(original);
 const form=n('form');const cols=n('div','edit-columns');for(const [code,label]of [['vi','TIẾNG VIỆT'],['en','ENGLISH']]){const col=n('div');col.append(n('h3','',label),field('Heading',code+'_title',p[code].title),field('Tóm tắt',code+'_summary',p[code].summary,true));cols.append(col);}form.append(cols);
 const topic=n('label','field','Chủ đề'),select=n('select');select.name='topic';for(const [value,label]of Object.entries(topicLabels)){const option=n('option','',label);option.value=value;option.selected=value===p.topic;select.append(option);}topic.append(select);form.append(topic,field('Tên nguồn','source_name',p.source_name),field('Link nguồn (HTTPS)','source_url',p.source_url),field('Ghi chú riêng','review_note',p.review_note,true));
 const review=n('label','review-check'),checkbox=n('input');checkbox.type='checkbox';checkbox.name='reviewed';review.append(checkbox,n('span','','Tui đã đọc nguồn, kiểm tra cả hai bản dịch và xác nhận bài không có chính trị hoặc nội dung nặng nề.'));form.append(review);
 const actions=n('div','editor-actions');for(const [action,label,cls]of [['published',p.status==='published'?'Lưu & cập nhật':'Duyệt & đăng','button'],['pending','Lưu bản nháp','button secondary'],['rejected',p.status==='published'?'Gỡ bài':'Loại bài','button danger']]){const b=n('button',cls,label);b.type='button';b.onclick=()=>save(form,action);actions.append(b);}const previewButton=n('button','button secondary','Xem trước');previewButton.type='button';actions.append(previewButton);form.append(actions,n('p','editor-note','Bài chờ duyệt và ghi chú riêng chỉ hiển thị cho admin.'));
 const preview=n('div','preview');preview.hidden=true;previewButton.onclick=()=>{preview.replaceChildren();const values=new FormData(form);for(const code of ['vi','en']){preview.append(n('span','eyebrow',code.toUpperCase()),n('h3','',values.get(code+'_title')),n('p','',values.get(code+'_summary')));}preview.hidden=!preview.hidden;};form.append(preview);form.onsubmit=e=>e.preventDefault();form.oninput=e=>{dirty=true;if(e.target!==checkbox)checkbox.checked=false;};root.append(form);
}
async function save(form,newStatus){const values=new FormData(form),reviewed=values.get('reviewed')==='on';if(newStatus==='published'&&!reviewed){message('Kiểm tra nguồn và đánh dấu xác nhận trước khi đăng nhé.');return;}
 const body={...selected,source_url:values.get('source_url'),source_name:values.get('source_name'),topic:values.get('topic'),review_note:values.get('review_note'),status:newStatus,reviewed,vi:{title:values.get('vi_title'),summary:values.get('vi_summary')},en:{title:values.get('en_title'),summary:values.get('en_summary')}};
 if(newStatus==='rejected'&&!confirm(selected.status==='published'?'Gỡ bài này khỏi feed?':'Loại bài này? Bạn vẫn có thể khôi phục sau.'))return;
 const buttons=form.querySelectorAll('button');buttons.forEach(b=>b.disabled=true);try{await api('admin/posts/'+selected.id,{method:'PUT',body:JSON.stringify(body)});dirty=false;await load();message(newStatus==='published'?'Đã đăng. Bài sẽ xuất hiện khi feed được tải lại.':newStatus==='rejected'?'Đã loại bài.':'Đã lưu bản nháp.');}catch(e){message(e.message);}finally{buttons.forEach(b=>b.disabled=false);}
}
$('login-form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;$('login-error').textContent='';try{await api('login',{method:'POST',body:JSON.stringify({password:new FormData(e.target).get('password')})});e.target.reset();loggedIn(true);await load();}catch(err){$('login-error').textContent=err.message;}finally{button.disabled=false;}};
$('logout').onclick=async()=>{if(!leave())return;try{await api('logout',{method:'POST',body:'{}'});loggedIn(false);}catch(e){message(e.message);}};
$('refresh').onclick=()=>{if(leave()){dirty=false;load();}};$('queue-more').onclick=()=>load(true);
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
api('admin/session').then(()=>{loggedIn(true);load();}).catch(()=>{});
