const cfg=window.ZUITOPIA||{},demo=cfg.DEMO!==false;
const copy={vi:{note:'Một góc nhỏ để tò mò.',all:'Dành cho bạn',space:'Vũ trụ',science:'Khoa học',nature:'Thiên nhiên',culture:'Nghệ thuật',everyday:'Đời sống',saved:'Đã lưu',heading:'Một chút điều hay',eyebrow:'FEED CỦA BẠN',welcome:'Hôm nay, đọc điều gì dễ chịu nhé.',welcomeText:'Tin tích cực và fact thú vị. Ngắn gọn, có nguồn.',aboutEye:'MỘT GÓC KHÁC',aboutTitle:'Còn nhiều điều để tò mò.',aboutText:'Không chính trị, không những câu chuyện nặng nề. Chỉ những điều thú vị đáng dành vài phút để đọc.',sourceNote:'Mỗi bài có nguồn để bạn tự đọc thêm. Thấy sai sót? Bạn có thể báo ngay dưới bài.',privacy:'Không quảng cáo. Không cần tài khoản.',contact:'Liên hệ',read:'Đọc nguồn',save:'Lưu bài',unsave:'Bỏ lưu',report:'Báo vấn đề',empty:'Chưa có bài ở đây. Ghé lại sau nhé.',emptySaved:'Chưa có bài đã lưu. Bấm biểu tượng lưu dưới một bài bạn thích.',more:'Xem thêm',demo:'Đang xem bài mẫu để thử giao diện. Chưa kết nối nguồn tin trực tiếp.',loading:'Đang tải…',error:'Chưa tải được bài. Bạn có thể thử tải lại trang.',contactTitle:'Liên hệ với Zuitopia',contactText:'Báo thông tin sai, bản dịch chưa đúng hoặc nội dung không phù hợp. Nhớ gửi kèm tên hoặc link bài nhé.',noEmail:'Địa chỉ liên hệ chưa được cấu hình.',fact:'Fact thú vị',savedLimit:'Bạn có thể lưu tối đa 100 bài.'},en:{note:'A little room for curiosity.',all:'For you',space:'Space',science:'Science',nature:'Nature',culture:'Arts & culture',everyday:'Everyday life',saved:'Saved',heading:'A little curiosity',eyebrow:'YOUR FEED',welcome:'Something pleasant to read today.',welcomeText:'Positive stories and interesting facts. Short, with sources.',aboutEye:'A DIFFERENT CORNER',aboutTitle:'There is still plenty to be curious about.',aboutText:'No politics or heavy stories. Just interesting things worth a few minutes of your day.',sourceNote:'Every post links to its source. Spotted a mistake? Report it below the post.',privacy:'No ads. No account needed.',contact:'Contact us',read:'Read source',save:'Save post',unsave:'Unsave',report:'Report an issue',empty:'No posts here yet. Check back soon.',emptySaved:'No saved posts yet. Save a post you like using the bookmark below it.',more:'Load more',demo:'Sample posts for exploring the interface. Live news is not connected yet.',loading:'Loading…',error:'Could not load posts. Please try refreshing the page.',contactTitle:'Contact Zuitopia',contactText:'Report an incorrect fact, translation or unsuitable content. Please include the post title or link.',noEmail:'A contact email has not been configured yet.',fact:'Interesting fact',savedLimit:'You can save up to 100 posts.'}};
function stored(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function persist(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{/* Browsing still works when storage is unavailable. */}}
let lang=stored('bf-lang','vi');if(!copy[lang])lang='vi';let saved=stored('bf-saved',[]);if(!Array.isArray(saved))saved=[];
let topic='all',posts=[],offset=0,hasMore=false,contactEmail=cfg.CONTACT_EMAIL||'',generation=0;
const $=id=>document.getElementById(id),t=()=>copy[lang];
const icons={all:'⌂',space:'✦',science:'⚗',nature:'❧',culture:'◈',everyday:'☀',saved:'▱'};
const bookmark='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M6 3h12v18l-6-4-6 4z"/></svg>';
function node(tag,className,content){const n=document.createElement(tag);if(className)n.className=className;if(content!==undefined)n.textContent=content;return n;}
function safeLink(url){try{const u=new URL(url);return u.protocol==='https:'?u.href:null}catch{return null}}
function emailLink(subject,body){return `mailto:${contactEmail}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;}
function labels(){document.documentElement.lang=lang;const c=t();for(const [id,key]of Object.entries({'brand-note':'note','eyebrow':'eyebrow','welcome-title':'welcome','welcome-text':'welcomeText','about-eyebrow':'aboutEye','about-title':'aboutTitle','about-text':'aboutText','source-note':'sourceNote','privacy-note':'privacy','contact':'contact','contact-title':'contactTitle','contact-text':'contactText','contact-unconfigured':'noEmail','more':'more'}))$(id).textContent=c[key];
 $('feed-heading').textContent=topic==='all'?c.heading:c[topic];document.querySelectorAll('[data-lang]').forEach(b=>{b.classList.toggle('active',b.dataset.lang===lang);b.setAttribute('aria-pressed',String(b.dataset.lang===lang));});
 $('topics').replaceChildren(...Object.keys(icons).map(key=>{const b=node('button','nav-button'+(topic===key?' active':''));b.type='button';b.append(node('span','nav-icon',icons[key]),node('span','',c[key]));b.querySelector('.nav-icon').setAttribute('aria-hidden','true');b.setAttribute('aria-pressed',String(topic===key));b.onclick=()=>{topic=key;labels();load();};return b;}));
 $('contact-email').hidden=!contactEmail;$('contact-unconfigured').hidden=!!contactEmail;if(contactEmail){$('contact-email').textContent=contactEmail;$('contact-email').href=emailLink('Zuitopia — contact','');}
 if(demo){$('notice').hidden=false;$('notice').textContent=c.demo;}
 render();
}
function card(p){const c=t(),content=p[lang]||p.en,article=node('article','post');article.id='post-'+p.id;
 const top=node('div','post-top'),meta=node('div','source-meta');meta.append(node('div','source-name',p.source_name),node('div','post-date',p.published_at?new Intl.DateTimeFormat(lang==='vi'?'vi-VN':'en-AU',{day:'numeric',month:'short',year:'numeric'}).format(new Date(p.published_at)):c.fact));
 top.append(node('div','source-icon',p.source_name.slice(0,1)),meta,node('span','topic-tag',c[p.topic]));article.append(top,node('h2','',content.title),node('p','',content.summary));
 const actions=node('div','post-actions'),url=safeLink(p.source_url);if(url){const a=node('a','source-link',c.read);a.href=url;a.target='_blank';a.rel='noopener noreferrer';actions.append(a);}
 const save=node('button','save-button'+(saved.includes(p.id)?' saved':''));save.type='button';save.innerHTML=bookmark;save.title=save.getAttribute('aria-label')||'';save.setAttribute('aria-label',saved.includes(p.id)?c.unsave:c.save);save.title=save.getAttribute('aria-label');save.setAttribute('aria-pressed',String(saved.includes(p.id)));
 save.onclick=()=>{if(saved.includes(p.id))saved=saved.filter(id=>id!==p.id);else {if(saved.length>=100){$('notice').hidden=false;$('notice').textContent=c.savedLimit;return;}saved.push(p.id);}persist('bf-saved',saved);if(topic==='saved')load();else render();};actions.append(save);
 const report=node('button','report-button',c.report);report.type='button';report.onclick=()=>{if(!contactEmail){$('contact-dialog').showModal();return;}const link=new URL(location.href);link.hash='post-'+p.id;location.href=emailLink('[Report] '+content.title,`Post ID: ${p.id}\nPost: ${link.href}\nSource: ${p.source_url}\n\n${lang==='vi'?'Vấn đề:':'Issue:'}\n`);};actions.append(report);article.append(actions);return article;
}
function render(){if(!posts.length){$('feed').replaceChildren(node('p','empty',topic==='saved'?t().emptySaved:t().empty));}else $('feed').replaceChildren(...posts.map(card));$('more').hidden=!hasMore;}
async function load(append=false){const my=++generation;if(!append){posts=[];offset=0;$('feed').replaceChildren(node('p','empty',t().loading));} $('more').disabled=true;
 try{let data;if(demo){data=await (await fetch('./demo.json')).json();data.posts=data.posts.filter(p=>topic==='saved'?saved.includes(p.id):topic==='all'||p.topic===topic);}else {
  if(topic==='saved'&&!saved.length){data={posts:[],has_more:false};}else {const params=new URLSearchParams({offset:String(offset)});if(topic==='saved')params.set('ids',saved.join(','));else params.set('topic',topic);const response=await fetch((cfg.API_BASE||'')+'/api/posts?'+params);if(!response.ok)throw new Error();data=await response.json();}
 }if(my!==generation)return;posts=append?[...posts,...data.posts]:data.posts;offset=posts.length;hasMore=!!data.has_more;render();
 }catch{if(my===generation){$('feed').replaceChildren(node('p','empty',t().error));$('more').hidden=true;}}finally{if(my===generation)$('more').disabled=false;}}
document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{lang=b.dataset.lang;persist('bf-lang',lang);labels();});
$('contact').onclick=e=>{e.preventDefault();$('contact-dialog').showModal();};document.querySelector('.dialog-close').onclick=()=>$('contact-dialog').close();$('more').onclick=()=>load(true);
labels();load();
if(!demo){fetch((cfg.API_BASE||'')+'/api/config').then(r=>r.json()).then(c=>{contactEmail=/^[^\s@?]+@[^\s@?]+\.[^\s@?]+$/.test(c.contact_email)?c.contact_email:'';const admin=safeLink(c.admin_url);if(admin){$('admin-link').href=admin;$('admin-link').hidden=false;}else if(location.hostname==='localhost'||location.hostname==='127.0.0.1'){$('admin-link').href='/admin/';$('admin-link').hidden=false;}labels();}).catch(()=>{});}else{$('admin-link').href='./admin/';$('admin-link').hidden=false;}
